% unit mean
meanfunction = {@meanMask, [0,1,0,0,0,0,0,0,0,0], {@meanDiscrete, n}};
theta.mean = [zeros(n,1)];

for i=1:n
   theta.mean(i) = mean(y(strcmp(data.country,countries{i}))); 
end

% unit trend
unit_length_scale = 4;
unit_output_scale = 0.5;
unit_error_covariance = {@covProd, {{@covMask, {1, {@covSEiso}}}, ...
                                    {@covMask, {2, {@covSEisoU}}}}};
theta.cov = [log(unit_length_scale); ... % 1
             log(unit_output_scale); ... % 2
             log(0.01)];                 % 3
         
% covariate effect (continuous)
% log(gdppc) and log(pop)
x_continuous_covariance = {@covMask, {[7,8], {@covSEard}}};
theta.cov = [theta.cov; ...
             log(std(data.gdppc));...    % 4
             log(std(data.pop)); ...     % 5
             log(0.5)];                  % 6

% covariate effect (binary)
% cat_rat, ccpr_rat, democratic, Civilwar2 and War
cat_binary_covariance = {@covMask, {[4], {@covSEiso}}};
theta.cov = [theta.cov; ...
             log(0.01); ...              % 7
             log(0.5)];                  % 8
         
ccpr_binary_covariance = {@covMask, {[5], {@covSEiso}}};
theta.cov = [theta.cov; ...
             log(0.01); ...              % 9
             log(0.5)];                  % 10
         
dem_binary_covariance = {@covMask, {[6], {@covSEiso}}};
theta.cov = [theta.cov; ...
             log(0.01); ...              % 11
             log(0.5)];                  % 12

cw2_binary_covariance = {@covMask, {[9], {@covSEiso}}};
theta.cov = [theta.cov; ...
             log(0.01); ...              % 13
             log(0.5)];                  % 14
         
war_binary_covariance = {@covMask, {[10], {@covSEiso}}};
theta.cov = [theta.cov; ...
             log(0.01); ...              % 15
             log(0.5)];                  % 16
         
% treatment effect (AIShame) 
AIShame_covariance = {@covMask, {[3], {@covSEiso}}};
theta.cov = [theta.cov; ...
             log(0.01); ...              % 17
             log(0.5)];                  % 18


covfunction = {@covSum, {unit_error_covariance, x_continuous_covariance, ...
            cat_binary_covariance, ccpr_binary_covariance,...
            dem_binary_covariance, ...
            cw2_binary_covariance, war_binary_covariance,...
            AIShame_covariance}};

likfunction = {@likGauss};
theta.lik = [log(0.5)];

prior.cov  = {[], ...
              [], ...
              @priorDelta, ...
              [],...
              [],...
              [],...
              @priorDelta, ...
              [], ...
              @priorDelta, ...
              [], ...
              @priorDelta, ...
              [], ...
              @priorDelta, ...
              [], ...
              @priorDelta, ...
              [], ...
              @priorDelta, ...
              []};  
prior.lik  = {[]};
prior.mean = cell(n,1);
prior.mean(:) = {@priorDelta};

inference_method = {@infPrior, @infExact, prior};
non_drift_idx = [2, 6, 8,10,12,14,16];
p.method = 'LBFGS';
p.length = 100;